#Sai Ruchitha Hardageri Thammareddy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment  # Name of the deployment
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: db-volume
        hostPath:
          path: /data/db
      containers:
      - name: mongodb # Name of the container
        image: sairuchithahtreddy/mongodb:latest
        ports:
        - containerPort: 27017
        volumeMounts: 
        - name: db-volume
          mountPath: /data/db