#Sai Ruchitha Hardageri Thammareddy
apiVersion: v1
kind: Service
metadata:
  name: flask-web # Name of the service
spec:
  selector:
    app: flask-web
  type: NodePort 
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30100