#Sai Ruchitha Hardageri Thammareddy
apiVersion: apps/v1
kind: Deployment  # Name of the deployment
metadata:
  name: webserver-deployment
  labels:
    app: flask-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      containers:
        - name: flask-web # Name of the container
          image: sairuchithahtreddy/flaskweb:latest
          ports:
            - containerPort: 8080